bandwidth_bounds:
  min:
  max:

delay_bounds:
  min:
  max:

uplink_queue_bounds:
  min:
  max:

replicate_logs:

location:

run_times: 3

username: francisyyan

schemes:
  - default_tcp
  - vegas
  - ledbat
  - pcc
  - quic
  - scream
  - sprout
  - taova
  - verus
