bandwidth_bounds:
  min:
  max:

delay_bounds:
  min:
  max:

uplink_queue_bounds:
  min:
  max:

uplink_loss_bounds:
  min:
  max:

downlink_loss_bounds:
  min:
  max:

replicate_logs:

location:

run_times:

username:

schemes:
  - default_tcp
  - vegas
  - bbr
  - ledbat
  - pcc
  - quic
  - scream
  - sprout
  - taova
  - verus
  - webrtc
