bandwidth_bounds:
  min:
  max:

delay_bounds:
  min:
  max:

uplink_loss_bounds:
  min: 0.0
  max: 0.1

replicate_logs:

location:

run_times: 3

username: francisyyan

schemes:
  - default_tcp
  - vegas
  - bbr
  - ledbat
  - pcc
  - quic
  - scream
  - sprout
  - taova
  - verus
