bandwidth_bounds:
  min: 5
  max: 40

delay_bounds:
  min: 0
  max: 50

uplink_queue_bounds:
  min: 10
  max: 500

uplink_loss_bounds:
  min: 0.0
  max: 0.1

replicate_logs: .

location: test

flows:

interval:

run_times: 3

username: vagrant

schemes:
  - default_tcp
  - vegas
  - bbr
  - kern_copa
